name: rocket_tracker
description: Track nearby rocket launches with map view and Google Maps directions.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.0
  url_launcher: ^6.3.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
